name: Run on workflows
on:
    schedule:
      - cron: "0 */6 * * *"
    push:
      branches: [ master ]
    workflow_dispatch:
    
env:
  api_key: "${{ secrets.api_key }}"
  token: "${{ secrets.token }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancelling duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: Set up Python 3.9
         uses: actions/setup-python@v2.2.2
         with:
           python-version: 3.9
       - name: cloning repo and install

         continue-on-error: true
         run: |
           pip3 install -r requirements.txt
          #  echo "api_key=${{ secrets.api_key }} | tee .env
          #  echo "token=${{ secrets.TOKEN }} | tee -a .env || echo "Proceeding with no bot"
          #  cat .env
       - name: Running
         timeout-minutes: 500
         continue-on-error: true
         run: |
           python3 -m bot
           echo "Magic Happened!!!!"
